-- P1.1: Stripe webhook idempotency table
create table if not exists public.stripe_events (
  event_id text primary key,
  event_type text not null,
  processed_at timestamptz not null default now()
);

alter table if exists public.stripe_events enable row level security;

-- No RLS needed: only service role accesses this table via API routes.

create index if not exists idx_stripe_events_type on public.stripe_events(event_type);
create index if not exists idx_stripe_events_processed_at on public.stripe_events(processed_at);

-- P1.2: Rate limiting table (in-database fallback; most limiting done in-memory in route handlers)
create table if not exists public.rate_limit_log (
  id bigint generated by default as identity primary key,
  route text not null,
  client_ip text not null,
  request_count integer not null default 1,
  window_start timestamptz not null default now(),
  created_at timestamptz not null default now()
);

alter table if exists public.rate_limit_log enable row level security;

create index if not exists idx_rate_limit_route_ip on public.rate_limit_log(route, client_ip);
create index if not exists idx_rate_limit_window on public.rate_limit_log(window_start);
