-- Simba Supabase production schema.
-- This migration replaces runtime table creation and repair.

create extension if not exists pgcrypto;

do $$ begin
  create type public.store_role as enum (
    'customer',
    'branch_staff',
    'branch_manager',
    'delivery_agent',
    'super_admin'
  );
exception when duplicate_object then null;
end $$;

do $$ begin
  create type public.order_status as enum (
    'pending',
    'awaiting_payment',
    'awaiting_confirmation',
    'processing',
    'ready_for_pickup',
    'shipped',
    'delivered',
    'cancelled'
  );
exception when duplicate_object then null;
end $$;

do $$ begin
  create type public.delivery_method as enum ('delivery', 'pickup');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type public.delivery_option as enum (
    'delivery_by_branch',
    'delivery_by_delivery_guy',
    'self_pickup'
  );
exception when duplicate_object then null;
end $$;

do $$ begin
  create type public.payment_method as enum (
    'card',
    'mtn_momo',
    'airtel_money',
    'cash_on_delivery'
  );
exception when duplicate_object then null;
end $$;

do $$ begin
  create type public.invitation_status as enum ('pending', 'accepted', 'revoked', 'expired');
exception when duplicate_object then null;
end $$;

create table if not exists public.branches (
  id bigint generated by default as identity primary key,
  name text not null unique,
  address text,
  short_address text,
  city text not null default 'Kigali',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  phone text,
  email text,
  role public.store_role not null default 'customer',
  default_branch_id bigint references public.branches(id) on delete set null,
  addresses jsonb not null default '[]'::jsonb,
  preferred_payment_method public.payment_method,
  no_show_flags integer not null default 0 check (no_show_flags >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text generated always as (
    lower(regexp_replace(regexp_replace(name, '[^a-zA-Z0-9]+', '-', 'g'), '(^-|-$)', '', 'g'))
  ) stored,
  price numeric(12,2) not null check (price >= 0),
  category text not null,
  subcategory_id integer,
  image text,
  unit text,
  description text,
  brand text,
  rating numeric(3,2) not null default 0 check (rating >= 0 and rating <= 5),
  discount integer not null default 0 check (discount >= 0 and discount <= 100),
  tags text[] not null default '{}',
  attributes jsonb not null default '{}'::jsonb,
  variations jsonb not null default '[]'::jsonb,
  options text[] not null default '{}',
  addons text[] not null default '{}',
  modifiers text[] not null default '{}',
  upsells bigint[] not null default '{}',
  cross_sells bigint[] not null default '{}',
  related_products bigint[] not null default '{}',
  recommended_products bigint[] not null default '{}',
  similar_products bigint[] not null default '{}',
  frequently_bought_together bigint[] not null default '{}',
  best_seller boolean not null default false,
  new_arrival boolean not null default false,
  featured boolean not null default false,
  on_sale boolean not null default false,
  backorder boolean not null default false,
  pre_order boolean not null default false,
  discontinued boolean not null default false,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.product_inventory (
  product_id bigint not null references public.products(id) on delete cascade,
  branch_id bigint not null references public.branches(id) on delete cascade,
  stock_count integer not null default 0 check (stock_count >= 0),
  available_for_delivery boolean not null default true,
  low_stock_threshold integer not null default 5 check (low_stock_threshold >= 0),
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now(),
  primary key (product_id, branch_id)
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  customer_name text,
  branch_id bigint references public.branches(id) on delete set null,
  assigned_branch_id bigint references public.branches(id) on delete set null,
  subtotal numeric(12,2) not null default 0 check (subtotal >= 0),
  shipping numeric(12,2) not null default 0 check (shipping >= 0),
  discount numeric(12,2) not null default 0 check (discount >= 0),
  deposit_amount numeric(12,2) not null default 0 check (deposit_amount >= 0),
  total numeric(12,2) not null check (total >= 0),
  delivery_method public.delivery_method not null default 'delivery',
  delivery_option public.delivery_option,
  address text,
  phone text,
  payment_method public.payment_method not null default 'mtn_momo',
  status public.order_status not null default 'pending',
  tracking_number text not null unique,
  pickup_time timestamptz,
  assigned_staff_id uuid references public.profiles(user_id) on delete set null,
  assigned_delivery_agent_id uuid references public.profiles(user_id) on delete set null,
  rating integer check (rating >= 1 and rating <= 5),
  review_comment text,
  review_branch_id bigint references public.branches(id) on delete set null,
  timeline jsonb not null default '[]'::jsonb,
  stripe_session_id text unique,
  payment_status text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  product_name text not null,
  price numeric(12,2) not null check (price >= 0),
  quantity integer not null check (quantity > 0),
  image text,
  unit text,
  created_at timestamptz not null default now()
);

create table if not exists public.cart_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  quantity integer not null check (quantity > 0),
  branch_id bigint references public.branches(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, product_id, branch_id)
);

create table if not exists public.invitations (
  id bigint generated by default as identity primary key,
  token text not null unique,
  role public.store_role not null,
  branch_id bigint references public.branches(id) on delete set null,
  invited_email text,
  note text,
  created_by uuid not null references auth.users(id) on delete cascade,
  inviter_role public.store_role,
  status public.invitation_status not null default 'pending',
  used_by uuid references auth.users(id) on delete set null,
  used_at timestamptz,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.site_visits (
  client_key text not null,
  visit_day date not null,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  path text,
  referrer text,
  user_agent text,
  created_at timestamptz not null default now(),
  primary key (client_key, visit_day)
);

-- Upgrade deployments that already contain FastAPI-created tables. CREATE TABLE
-- IF NOT EXISTS intentionally leaves those tables untouched, so every column
-- referenced by indexes, views, RLS policies, and route handlers is added here.
alter table if exists public.branches add column if not exists address text;
alter table if exists public.branches add column if not exists short_address text;
alter table if exists public.branches add column if not exists city text default 'Kigali';
alter table if exists public.branches add column if not exists is_active boolean default true;
alter table if exists public.branches add column if not exists created_at timestamptz default now();
alter table if exists public.branches add column if not exists updated_at timestamptz default now();

delete from public.branches a
using public.branches b
where a.ctid < b.ctid
  and a.name = b.name;

create unique index if not exists idx_branches_name_unique on public.branches(name);

insert into public.branches (name, address, short_address, city)
values
  ('Simba Supermarket Remera', '3336+MHV Union Trade Centre, 1 KN 4 Ave, Kigali', 'Union Trade Centre, KN 4 Ave', 'Kigali'),
  ('Simba Supermarket Kimironko', '342F+3V5, Kimironko, Kigali, RW', 'Kimironko, Kigali', 'Kigali'),
  ('Simba Supermarket Kacyiru', 'KN 5 Rd, Kigali', 'KN 5 Rd', 'Kigali'),
  ('Simba Supermarket Nyamirambo', '23H4+26V, Kigali', 'Nyamirambo, Kigali', 'Kigali'),
  ('Simba Supermarket Gikondo', '24G3+MCV, Kigali', 'Gikondo, Kigali', 'Kigali'),
  ('Simba Supermarket Kanombe', 'KK 35 Ave, Kigali', 'KK 35 Ave', 'Kigali'),
  ('Simba Supermarket Kinyinya', 'KG 541 St, Kigali', 'KG 541 St', 'Kigali'),
  ('Simba Supermarket Kibagabaga', '24Q5+R2R, Kigali', 'Kibagabaga, Kigali', 'Kigali'),
  ('Simba Supermarket Nyanza', '24XF+XVV, KG 192 St, Kigali', 'KG 192 St', 'Kigali')
on conflict (name) do update set
  address = excluded.address,
  short_address = excluded.short_address,
  city = excluded.city,
  is_active = true,
  updated_at = now();

alter table if exists public.profiles add column if not exists display_name text;
alter table if exists public.profiles add column if not exists phone text;
alter table if exists public.profiles add column if not exists email text;
alter table if exists public.profiles add column if not exists role public.store_role default 'customer';
alter table if exists public.profiles add column if not exists default_branch_id bigint;
alter table if exists public.profiles add column if not exists addresses jsonb default '[]'::jsonb;
alter table if exists public.profiles add column if not exists preferred_payment_method public.payment_method;
alter table if exists public.profiles add column if not exists no_show_flags integer default 0;
alter table if exists public.profiles add column if not exists created_at timestamptz default now();
alter table if exists public.profiles add column if not exists updated_at timestamptz default now();

alter table if exists public.products add column if not exists subcategory_id integer;
alter table if exists public.products add column if not exists image text;
alter table if exists public.products add column if not exists unit text;
alter table if exists public.products add column if not exists description text;
alter table if exists public.products add column if not exists brand text;
alter table if exists public.products add column if not exists rating numeric(3,2) default 0;
alter table if exists public.products add column if not exists discount integer default 0;
alter table if exists public.products add column if not exists tags text[] default '{}';
alter table if exists public.products add column if not exists attributes jsonb default '{}'::jsonb;
alter table if exists public.products add column if not exists variations jsonb default '[]'::jsonb;
alter table if exists public.products add column if not exists options text[] default '{}';
alter table if exists public.products add column if not exists addons text[] default '{}';
alter table if exists public.products add column if not exists modifiers text[] default '{}';
alter table if exists public.products add column if not exists upsells bigint[] default '{}';
alter table if exists public.products add column if not exists cross_sells bigint[] default '{}';
alter table if exists public.products add column if not exists related_products bigint[] default '{}';
alter table if exists public.products add column if not exists recommended_products bigint[] default '{}';
alter table if exists public.products add column if not exists similar_products bigint[] default '{}';
alter table if exists public.products add column if not exists frequently_bought_together bigint[] default '{}';
alter table if exists public.products add column if not exists best_seller boolean default false;
alter table if exists public.products add column if not exists new_arrival boolean default false;
alter table if exists public.products add column if not exists featured boolean default false;
alter table if exists public.products add column if not exists on_sale boolean default false;
alter table if exists public.products add column if not exists backorder boolean default false;
alter table if exists public.products add column if not exists pre_order boolean default false;
alter table if exists public.products add column if not exists discontinued boolean default false;
alter table if exists public.products add column if not exists created_by uuid;
alter table if exists public.products add column if not exists updated_by uuid;
alter table if exists public.products add column if not exists created_at timestamptz default now();
alter table if exists public.products add column if not exists updated_at timestamptz default now();

do $$
begin
  if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'products' and column_name = 'tags' and udt_name <> '_text') then
    alter table public.products alter column tags drop default;
    alter table public.products alter column tags type text[] using '{}'::text[];
  end if;
  if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'products' and column_name = 'options' and udt_name <> '_text') then
    alter table public.products alter column options drop default;
    alter table public.products alter column options type text[] using '{}'::text[];
  end if;
  if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'products' and column_name = 'addons' and udt_name <> '_text') then
    alter table public.products alter column addons drop default;
    alter table public.products alter column addons type text[] using '{}'::text[];
  end if;
  if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'products' and column_name = 'modifiers' and udt_name <> '_text') then
    alter table public.products alter column modifiers drop default;
    alter table public.products alter column modifiers type text[] using '{}'::text[];
  end if;
  if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'products' and column_name = 'upsells' and udt_name <> '_int8') then
    alter table public.products alter column upsells drop default;
    alter table public.products alter column upsells type bigint[] using '{}'::bigint[];
  end if;
  if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'products' and column_name = 'cross_sells' and udt_name <> '_int8') then
    alter table public.products alter column cross_sells drop default;
    alter table public.products alter column cross_sells type bigint[] using '{}'::bigint[];
  end if;
  if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'products' and column_name = 'related_products' and udt_name <> '_int8') then
    alter table public.products alter column related_products drop default;
    alter table public.products alter column related_products type bigint[] using '{}'::bigint[];
  end if;
  if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'products' and column_name = 'recommended_products' and udt_name <> '_int8') then
    alter table public.products alter column recommended_products drop default;
    alter table public.products alter column recommended_products type bigint[] using '{}'::bigint[];
  end if;
  if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'products' and column_name = 'similar_products' and udt_name <> '_int8') then
    alter table public.products alter column similar_products drop default;
    alter table public.products alter column similar_products type bigint[] using '{}'::bigint[];
  end if;
  if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'products' and column_name = 'frequently_bought_together' and udt_name <> '_int8') then
    alter table public.products alter column frequently_bought_together drop default;
    alter table public.products alter column frequently_bought_together type bigint[] using '{}'::bigint[];
  end if;
  if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'products' and column_name = 'attributes' and udt_name <> 'jsonb') then
    alter table public.products alter column attributes drop default;
    alter table public.products alter column attributes type jsonb using '{}'::jsonb;
  end if;
  if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'products' and column_name = 'variations' and udt_name <> 'jsonb') then
    alter table public.products alter column variations drop default;
    alter table public.products alter column variations type jsonb using '[]'::jsonb;
  end if;
end $$;

alter table if exists public.profiles alter column role set default 'customer';
alter table if exists public.products alter column tags set default '{}';
alter table if exists public.products alter column attributes set default '{}'::jsonb;
alter table if exists public.products alter column variations set default '[]'::jsonb;
alter table if exists public.products alter column options set default '{}';
alter table if exists public.products alter column addons set default '{}';
alter table if exists public.products alter column modifiers set default '{}';
alter table if exists public.products alter column upsells set default '{}';
alter table if exists public.products alter column cross_sells set default '{}';
alter table if exists public.products alter column related_products set default '{}';
alter table if exists public.products alter column recommended_products set default '{}';
alter table if exists public.products alter column similar_products set default '{}';
alter table if exists public.products alter column frequently_bought_together set default '{}';

alter table if exists public.product_inventory add column if not exists product_id bigint;
alter table if exists public.product_inventory add column if not exists branch_id bigint;
alter table if exists public.product_inventory add column if not exists stock_count integer default 0;
alter table if exists public.product_inventory add column if not exists available_for_delivery boolean default true;
alter table if exists public.product_inventory add column if not exists low_stock_threshold integer default 5;
alter table if exists public.product_inventory add column if not exists updated_by uuid;
alter table if exists public.product_inventory add column if not exists updated_at timestamptz default now();

alter table if exists public.orders add column if not exists customer_name text;
alter table if exists public.orders add column if not exists branch_id bigint;
alter table if exists public.orders add column if not exists assigned_branch_id bigint;
alter table if exists public.orders add column if not exists subtotal numeric(12,2) default 0;
alter table if exists public.orders add column if not exists shipping numeric(12,2) default 0;
alter table if exists public.orders add column if not exists discount numeric(12,2) default 0;
alter table if exists public.orders add column if not exists deposit_amount numeric(12,2) default 0;
alter table if exists public.orders add column if not exists total numeric(12,2) default 0;
alter table if exists public.orders add column if not exists delivery_method public.delivery_method default 'delivery';
alter table if exists public.orders add column if not exists delivery_option public.delivery_option;
alter table if exists public.orders add column if not exists address text;
alter table if exists public.orders add column if not exists phone text;
alter table if exists public.orders add column if not exists payment_method public.payment_method default 'mtn_momo';
alter table if exists public.orders add column if not exists status public.order_status default 'pending';
alter table if exists public.orders add column if not exists tracking_number text;
alter table if exists public.orders add column if not exists pickup_time timestamptz;
alter table if exists public.orders add column if not exists assigned_staff_id uuid;
alter table if exists public.orders add column if not exists assigned_delivery_agent_id uuid;
alter table if exists public.orders add column if not exists rating integer;
alter table if exists public.orders add column if not exists review_comment text;
alter table if exists public.orders add column if not exists review_branch_id bigint;
alter table if exists public.orders add column if not exists timeline jsonb default '[]'::jsonb;
alter table if exists public.orders add column if not exists stripe_session_id text;
alter table if exists public.orders add column if not exists payment_status text;
alter table if exists public.orders add column if not exists metadata jsonb default '{}'::jsonb;
alter table if exists public.orders add column if not exists created_at timestamptz default now();
alter table if exists public.orders add column if not exists updated_at timestamptz default now();

do $$
begin
  if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'orders' and column_name = 'timeline' and udt_name <> 'jsonb') then
    alter table public.orders alter column timeline type jsonb using '[]'::jsonb;
  end if;
  if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'orders' and column_name = 'metadata' and udt_name <> 'jsonb') then
    alter table public.orders alter column metadata type jsonb using '{}'::jsonb;
  end if;
  if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'orders' and column_name = 'assigned_staff_id' and udt_name <> 'uuid') then
    alter table public.orders alter column assigned_staff_id type uuid using (
      case
        when assigned_staff_id::text ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
        then assigned_staff_id::text::uuid
        else null
      end
    );
  end if;
  if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'orders' and column_name = 'assigned_delivery_agent_id' and udt_name <> 'uuid') then
    alter table public.orders alter column assigned_delivery_agent_id type uuid using (
      case
        when assigned_delivery_agent_id::text ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
        then assigned_delivery_agent_id::text::uuid
        else null
      end
    );
  end if;
end $$;

alter table if exists public.order_items add column if not exists order_id bigint;
alter table if exists public.order_items add column if not exists product_id bigint;
alter table if exists public.order_items add column if not exists product_name text;
alter table if exists public.order_items add column if not exists price numeric(12,2) default 0;
alter table if exists public.order_items add column if not exists quantity integer default 1;
alter table if exists public.order_items add column if not exists image text;
alter table if exists public.order_items add column if not exists unit text;
alter table if exists public.order_items add column if not exists created_at timestamptz default now();

alter table if exists public.cart_items add column if not exists branch_id bigint;
alter table if exists public.cart_items add column if not exists created_at timestamptz default now();
alter table if exists public.cart_items add column if not exists updated_at timestamptz default now();

alter table if exists public.invitations add column if not exists branch_id bigint;
alter table if exists public.invitations add column if not exists invited_email text;
alter table if exists public.invitations add column if not exists note text;
alter table if exists public.invitations add column if not exists created_by uuid;
alter table if exists public.invitations add column if not exists inviter_role public.store_role;
alter table if exists public.invitations add column if not exists status public.invitation_status default 'pending';
alter table if exists public.invitations add column if not exists used_by uuid;
alter table if exists public.invitations add column if not exists used_at timestamptz;
alter table if exists public.invitations add column if not exists expires_at timestamptz;
alter table if exists public.invitations add column if not exists created_at timestamptz default now();
alter table if exists public.invitations add column if not exists updated_at timestamptz default now();

do $$
begin
  if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'invitations' and column_name = 'created_by' and udt_name <> 'uuid') then
    alter table public.invitations alter column created_by drop not null;
    alter table public.invitations alter column created_by type uuid using (
      case
        when created_by::text ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
        then created_by::text::uuid
        else null
      end
    );
  end if;
  if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'invitations' and column_name = 'used_by' and udt_name <> 'uuid') then
    alter table public.invitations alter column used_by drop not null;
    alter table public.invitations alter column used_by type uuid using (
      case
        when used_by::text ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
        then used_by::text::uuid
        else null
      end
    );
  end if;
end $$;

alter table if exists public.site_visits add column if not exists client_key text;
alter table if exists public.site_visits add column if not exists visit_day date;
alter table if exists public.site_visits add column if not exists first_seen_at timestamptz default now();
alter table if exists public.site_visits add column if not exists last_seen_at timestamptz default now();
alter table if exists public.site_visits add column if not exists path text;
alter table if exists public.site_visits add column if not exists referrer text;
alter table if exists public.site_visits add column if not exists user_agent text;
alter table if exists public.site_visits add column if not exists created_at timestamptz default now();

do $$
begin
  if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'profiles' and column_name = 'default_branch') then
    update public.profiles p
    set default_branch_id = b.id
    from public.branches b
    where p.default_branch_id is null
      and p.default_branch::text = b.name;
  end if;
  if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'orders' and column_name = 'branch') then
    update public.orders o
    set branch_id = b.id
    from public.branches b
    where o.branch_id is null
      and o.branch::text = b.name;
  end if;
  if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'orders' and column_name = 'assigned_branch') then
    update public.orders o
    set assigned_branch_id = b.id
    from public.branches b
    where o.assigned_branch_id is null
      and o.assigned_branch::text = b.name;
  end if;
  if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'orders' and column_name = 'review_branch') then
    update public.orders o
    set review_branch_id = b.id
    from public.branches b
    where o.review_branch_id is null
      and o.review_branch::text = b.name;
  end if;
  if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'cart_items' and column_name = 'branch') then
    update public.cart_items c
    set branch_id = b.id
    from public.branches b
    where c.branch_id is null
      and c.branch::text = b.name;
  end if;
  if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'invitations' and column_name = 'branch') then
    update public.invitations i
    set branch_id = b.id
    from public.branches b
    where i.branch_id is null
      and i.branch::text = b.name;
  end if;
end $$;

delete from public.product_inventory a
using public.product_inventory b
where a.ctid < b.ctid
  and a.product_id = b.product_id
  and a.branch_id = b.branch_id;

delete from public.site_visits a
using public.site_visits b
where a.ctid < b.ctid
  and a.client_key = b.client_key
  and a.visit_day = b.visit_day;

create index if not exists idx_profiles_role on public.profiles(role);
create index if not exists idx_profiles_branch on public.profiles(default_branch_id);
create index if not exists idx_products_category on public.products(category);
create index if not exists idx_products_brand on public.products(brand);
create index if not exists idx_products_featured on public.products(featured) where discontinued = false;
create index if not exists idx_products_search on public.products using gin (
  to_tsvector('simple', coalesce(name, '') || ' ' || coalesce(brand, '') || ' ' || coalesce(category, '') || ' ' || coalesce(description, ''))
);
create index if not exists idx_product_inventory_branch on public.product_inventory(branch_id);
create unique index if not exists idx_product_inventory_product_branch on public.product_inventory(product_id, branch_id);
create index if not exists idx_orders_user on public.orders(user_id);
create index if not exists idx_orders_status on public.orders(status);
create index if not exists idx_orders_branch on public.orders(branch_id);
create index if not exists idx_orders_assigned_branch on public.orders(assigned_branch_id);
create index if not exists idx_orders_delivery_agent on public.orders(assigned_delivery_agent_id);
create index if not exists idx_order_items_order on public.order_items(order_id);
create index if not exists idx_cart_items_user on public.cart_items(user_id);
create index if not exists idx_invitations_created_by on public.invitations(created_by);
create index if not exists idx_invitations_status on public.invitations(status);
create index if not exists idx_site_visits_day on public.site_visits(visit_day);
create unique index if not exists idx_site_visits_client_day on public.site_visits(client_key, visit_day);

do $$
begin
  begin
    alter table public.profiles
      add constraint profiles_default_branch_id_fkey
      foreign key (default_branch_id) references public.branches(id) on delete set null;
  exception when others then null;
  end;

  begin
    alter table public.product_inventory
      add constraint product_inventory_product_id_fkey
      foreign key (product_id) references public.products(id) on delete cascade;
  exception when others then null;
  end;

  begin
    alter table public.product_inventory
      add constraint product_inventory_branch_id_fkey
      foreign key (branch_id) references public.branches(id) on delete cascade;
  exception when others then null;
  end;

  begin
    alter table public.orders
      add constraint orders_branch_id_fkey
      foreign key (branch_id) references public.branches(id) on delete set null;
  exception when others then null;
  end;

  begin
    alter table public.orders
      add constraint orders_assigned_branch_id_fkey
      foreign key (assigned_branch_id) references public.branches(id) on delete set null;
  exception when others then null;
  end;

  begin
    alter table public.orders
      add constraint orders_review_branch_id_fkey
      foreign key (review_branch_id) references public.branches(id) on delete set null;
  exception when others then null;
  end;

  begin
    alter table public.orders
      add constraint orders_assigned_staff_id_fkey
      foreign key (assigned_staff_id) references public.profiles(user_id) on delete set null;
  exception when others then null;
  end;

  begin
    alter table public.orders
      add constraint orders_assigned_delivery_agent_id_fkey
      foreign key (assigned_delivery_agent_id) references public.profiles(user_id) on delete set null;
  exception when others then null;
  end;

  begin
    alter table public.order_items
      add constraint order_items_order_id_fkey
      foreign key (order_id) references public.orders(id) on delete cascade;
  exception when others then null;
  end;

  begin
    alter table public.order_items
      add constraint order_items_product_id_fkey
      foreign key (product_id) references public.products(id) on delete set null;
  exception when others then null;
  end;

  begin
    alter table public.cart_items
      add constraint cart_items_product_id_fkey
      foreign key (product_id) references public.products(id) on delete cascade;
  exception when others then null;
  end;

  begin
    alter table public.cart_items
      add constraint cart_items_branch_id_fkey
      foreign key (branch_id) references public.branches(id) on delete set null;
  exception when others then null;
  end;

  begin
    alter table public.invitations
      add constraint invitations_branch_id_fkey
      foreign key (branch_id) references public.branches(id) on delete set null;
  exception when others then null;
  end;
end $$;

insert into public.product_inventory (product_id, branch_id, stock_count, available_for_delivery)
select p.id, b.id, 25, true
from public.products p
cross join public.branches b
where coalesce(p.discontinued, false) = false
on conflict (product_id, branch_id) do nothing;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_branches_updated_at on public.branches;
create trigger set_branches_updated_at before update on public.branches
for each row execute function public.set_updated_at();

drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists set_products_updated_at on public.products;
create trigger set_products_updated_at before update on public.products
for each row execute function public.set_updated_at();

drop trigger if exists set_product_inventory_updated_at on public.product_inventory;
create trigger set_product_inventory_updated_at before update on public.product_inventory
for each row execute function public.set_updated_at();

drop trigger if exists set_orders_updated_at on public.orders;
create trigger set_orders_updated_at before update on public.orders
for each row execute function public.set_updated_at();

drop trigger if exists set_cart_items_updated_at on public.cart_items;
create trigger set_cart_items_updated_at before update on public.cart_items
for each row execute function public.set_updated_at();

drop trigger if exists set_invitations_updated_at on public.invitations;
create trigger set_invitations_updated_at before update on public.invitations
for each row execute function public.set_updated_at();

create or replace function public.current_role()
returns public.store_role
language sql
security definer
set search_path = public
stable
as $$
  select coalesce(
    (
      select case
        when role::text in ('customer', 'branch_staff', 'branch_manager', 'delivery_agent', 'super_admin')
        then role::text::public.store_role
        else 'customer'::public.store_role
      end
      from public.profiles
      where user_id::text = auth.uid()::text
    ),
    'customer'::public.store_role
  );
$$;

create or replace function public.current_branch_id()
returns bigint
language sql
security definer
set search_path = public
stable
as $$
  select default_branch_id from public.profiles where user_id::text = auth.uid()::text;
$$;

create or replace function public.is_super_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select public.current_role() = 'super_admin'::public.store_role;
$$;

create or replace function public.can_access_dashboard()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select public.current_role() in (
    'super_admin'::public.store_role,
    'branch_manager'::public.store_role,
    'branch_staff'::public.store_role,
    'delivery_agent'::public.store_role
  );
$$;

create or replace function public.is_branch_staff()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select public.current_role() in (
    'branch_manager'::public.store_role,
    'branch_staff'::public.store_role,
    'delivery_agent'::public.store_role
  );
$$;

create or replace function public.can_access_order(target public.orders)
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select
    public.is_super_admin()
    or target.user_id::text = auth.uid()::text
    or (
      public.current_role() in ('branch_manager'::public.store_role, 'branch_staff'::public.store_role)
      and public.current_branch_id() is not null
      and (target.branch_id = public.current_branch_id() or target.assigned_branch_id = public.current_branch_id())
    )
    or (
      public.current_role() = 'delivery_agent'::public.store_role
      and (
        target.assigned_delivery_agent_id::text = auth.uid()::text
        or (
          public.current_branch_id() is not null
          and (target.branch_id = public.current_branch_id() or target.assigned_branch_id = public.current_branch_id())
        )
      )
    );
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (user_id, email, display_name)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'display_name', new.raw_user_meta_data ->> 'name', split_part(new.email, '@', 1))
  )
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace view public.product_catalog as
select
  p.id,
  p.name,
  p.price,
  p.category,
  p.subcategory_id,
  p.image,
  p.unit,
  p.description,
  p.brand,
  p.rating,
  p.discount,
  p.tags,
  p.attributes,
  p.variations,
  p.options,
  p.addons,
  p.modifiers,
  p.upsells,
  p.cross_sells,
  p.related_products,
  p.recommended_products,
  p.similar_products,
  p.frequently_bought_together,
  p.best_seller,
  p.new_arrival,
  p.featured,
  p.on_sale,
  p.backorder,
  p.pre_order,
  p.discontinued,
  p.created_by,
  p.updated_by,
  p.created_at,
  p.updated_at,
  coalesce(sum(pi.stock_count), 0)::integer as stock_count,
  coalesce(bool_or(pi.stock_count > 0), false) as in_stock,
  null::text as branch,
  coalesce(bool_or(pi.available_for_delivery), true) as available_for_delivery,
  coalesce(
    jsonb_object_agg(b.name, pi.stock_count) filter (where b.name is not null),
    '{}'::jsonb
  ) as branch_stock,
  (coalesce(sum(pi.stock_count), 0) <= 0)::boolean as out_of_stock,
  coalesce(bool_or(pi.stock_count > 0 and pi.stock_count <= pi.low_stock_threshold), false) as low_stock
from public.products p
left join public.product_inventory pi on pi.product_id = p.id
left join public.branches b on b.id = pi.branch_id
group by p.id;

create or replace view public.branch_review_summary as
select
  b.name as branch,
  coalesce(round(avg(o.rating)::numeric, 2), 0)::numeric as rating,
  count(o.rating)::integer as review_count,
  count(o.id)::integer as recent_orders
from public.branches b
left join public.orders o on o.review_branch_id = b.id or o.branch_id = b.id or o.assigned_branch_id = b.id
where b.is_active = true
group by b.id, b.name
order by b.name;

alter table public.branches enable row level security;
alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.product_inventory enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.cart_items enable row level security;
alter table public.invitations enable row level security;
alter table public.site_visits enable row level security;

drop policy if exists "branches public read" on public.branches;
create policy "branches public read" on public.branches
for select using (is_active = true or public.can_access_dashboard());

drop policy if exists "branches super admin write" on public.branches;
create policy "branches super admin write" on public.branches
for all using (public.is_super_admin()) with check (public.is_super_admin());

drop policy if exists "profiles own read" on public.profiles;
create policy "profiles own read" on public.profiles
for select using (
  user_id::text = auth.uid()::text
  or public.is_super_admin()
  or (
    public.can_access_dashboard()
    and default_branch_id = public.current_branch_id()
  )
);

drop policy if exists "profiles own insert" on public.profiles;
create policy "profiles own insert" on public.profiles
for insert with check (
  public.is_super_admin()
  or (
    user_id::text = auth.uid()::text
    and role::text = 'customer'
  )
);

drop policy if exists "profiles own update" on public.profiles;
create policy "profiles own update" on public.profiles
for update using (
  user_id::text = auth.uid()::text
  or public.is_super_admin()
) with check (
  public.is_super_admin()
  or (
    user_id::text = auth.uid()::text
    and role::text = public.current_role()::text
    and (
      public.current_role() = 'customer'::public.store_role
      or default_branch_id = public.current_branch_id()
    )
  )
);

drop policy if exists "products public read" on public.products;
create policy "products public read" on public.products
for select using (discontinued = false or public.can_access_dashboard());

drop policy if exists "products staff insert" on public.products;
create policy "products staff insert" on public.products
for insert with check (
  public.current_role() in ('super_admin'::public.store_role, 'branch_manager'::public.store_role, 'branch_staff'::public.store_role)
);

drop policy if exists "products staff update" on public.products;
create policy "products staff update" on public.products
for update using (
  public.current_role() in ('super_admin'::public.store_role, 'branch_manager'::public.store_role, 'branch_staff'::public.store_role)
) with check (
  public.current_role() in ('super_admin'::public.store_role, 'branch_manager'::public.store_role, 'branch_staff'::public.store_role)
);

drop policy if exists "products super admin delete" on public.products;
create policy "products super admin delete" on public.products
for delete using (public.is_super_admin());

drop policy if exists "inventory public read" on public.product_inventory;
create policy "inventory public read" on public.product_inventory
for select using (true);

drop policy if exists "inventory staff write" on public.product_inventory;
create policy "inventory staff write" on public.product_inventory
for all using (
  public.is_super_admin()
  or (
    public.current_role() in ('branch_manager'::public.store_role, 'branch_staff'::public.store_role)
    and branch_id = public.current_branch_id()
  )
) with check (
  public.is_super_admin()
  or (
    public.current_role() in ('branch_manager'::public.store_role, 'branch_staff'::public.store_role)
    and branch_id = public.current_branch_id()
  )
);

drop policy if exists "orders scoped read" on public.orders;
create policy "orders scoped read" on public.orders
for select using (public.can_access_order(orders));

drop policy if exists "orders own insert" on public.orders;
create policy "orders own insert" on public.orders
for insert with check (user_id::text = auth.uid()::text or public.is_super_admin());

drop policy if exists "orders scoped update" on public.orders;
create policy "orders scoped update" on public.orders
for update using (public.can_access_order(orders)) with check (public.can_access_order(orders));

drop policy if exists "orders super admin delete" on public.orders;
create policy "orders super admin delete" on public.orders
for delete using (public.is_super_admin());

drop policy if exists "order items scoped read" on public.order_items;
create policy "order items scoped read" on public.order_items
for select using (
  exists (
    select 1 from public.orders o
    where o.id = order_items.order_id
    and public.can_access_order(o)
  )
);

drop policy if exists "order items scoped insert" on public.order_items;
create policy "order items scoped insert" on public.order_items
for insert with check (
  exists (
    select 1 from public.orders o
    where o.id = order_items.order_id
    and public.can_access_order(o)
  )
);

drop policy if exists "order items scoped update" on public.order_items;
create policy "order items scoped update" on public.order_items
for update using (
  exists (
    select 1 from public.orders o
    where o.id = order_items.order_id
    and public.can_access_order(o)
  )
) with check (
  exists (
    select 1 from public.orders o
    where o.id = order_items.order_id
    and public.can_access_order(o)
  )
);

drop policy if exists "cart own access" on public.cart_items;
create policy "cart own access" on public.cart_items
for all using (user_id::text = auth.uid()::text) with check (user_id::text = auth.uid()::text);

drop policy if exists "invitations scoped read" on public.invitations;
create policy "invitations scoped read" on public.invitations
for select using (
  public.is_super_admin()
  or created_by::text = auth.uid()::text
  or (
    public.can_access_dashboard()
    and branch_id = public.current_branch_id()
  )
);

drop policy if exists "invitations scoped insert" on public.invitations;
create policy "invitations scoped insert" on public.invitations
for insert with check (
  public.is_super_admin()
  or (
    public.current_role() in ('branch_manager'::public.store_role, 'branch_staff'::public.store_role, 'delivery_agent'::public.store_role)
    and branch_id = public.current_branch_id()
  )
);

drop policy if exists "invitations scoped update" on public.invitations;
create policy "invitations scoped update" on public.invitations
for update using (
  public.is_super_admin()
  or created_by::text = auth.uid()::text
  or used_by::text = auth.uid()::text
) with check (
  public.is_super_admin()
  or created_by::text = auth.uid()::text
  or used_by::text = auth.uid()::text
);

drop policy if exists "site visits anonymous insert" on public.site_visits;
create policy "site visits anonymous insert" on public.site_visits
for insert with check (true);

drop policy if exists "site visits anonymous update" on public.site_visits;
create policy "site visits anonymous update" on public.site_visits
for update using (true) with check (true);

drop policy if exists "site visits dashboard read" on public.site_visits;
create policy "site visits dashboard read" on public.site_visits
for select using (public.can_access_dashboard());

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  ('product-images', 'product-images', true, 10485760, array['image/jpeg', 'image/png', 'image/webp', 'image/gif']),
  ('blog-media', 'blog-media', true, 10485760, array['image/jpeg', 'image/png', 'image/webp', 'image/gif']),
  ('private-documents', 'private-documents', false, 26214400, null)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "public product images read" on storage.objects;
create policy "public product images read" on storage.objects
for select using (bucket_id in ('product-images', 'blog-media'));

drop policy if exists "dashboard media write" on storage.objects;
create policy "dashboard media write" on storage.objects
for insert with check (
  bucket_id in ('product-images', 'blog-media')
  and public.can_access_dashboard()
);

drop policy if exists "dashboard media update" on storage.objects;
create policy "dashboard media update" on storage.objects
for update using (
  bucket_id in ('product-images', 'blog-media')
  and public.can_access_dashboard()
) with check (
  bucket_id in ('product-images', 'blog-media')
  and public.can_access_dashboard()
);

drop policy if exists "dashboard media delete" on storage.objects;
create policy "dashboard media delete" on storage.objects
for delete using (
  bucket_id in ('product-images', 'blog-media')
  and public.can_access_dashboard()
);

drop policy if exists "private documents owner read" on storage.objects;
create policy "private documents owner read" on storage.objects
for select using (
  bucket_id = 'private-documents'
  and (owner::text = auth.uid()::text or public.is_super_admin())
);
